### ISSUE TITLE
Xtables-addon

### ISSUE THREAD

**Issue by ghost** [yomguy/linux-RT-config#1]
Hmm. The package shipped with a symbolic link /lib/modules/3.10.10-amd64-yomguy-rt7/source
 However, I can not read the target: No such file or directory
 Therefore, I am deleting /lib/modules/3.10.10-amd64-yomguy-rt7/source

Running depmod.
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/dkms 3.10.10-amd64-yomguy-rt7 /boot/vmlinuz-3.10.10-amd64-yomguy-rt7
Error!  Build of xt_ACCOUNT.ko failed for: 3.10.10-amd64-yomguy-rt7 (x86_64)
Consult the make.log in the build directory
/var/lib/dkms/xtables-addons/1.42/build/ for more information.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 3.10.10-amd64-yomguy-rt7 /boot/vmlinuz-3.10.10-amd64-yomguy-rt7
update-initramfs: Generating /boot/initrd.img-3.10.10-amd64-yomguy-rt7
run-parts: executing /etc/kernel/postinst.d/zz-update-grub 3.10.10-amd64-yomguy-rt7 /boot/vmlinuz-3.10.10-amd64-yomguy-rt7
Generating grub.cfg ...
Found linux image: /boot/vmlinuz-3.10.10-amd64-yomguy-rt7
Found initrd image: /boot/initrd.img-3.10.10-amd64-yomguy-rt7
Found linux image: /boot/vmlinuz-3.2.0-4-rt-amd64
Found initrd image: /boot/initrd.img-3.2.0-4-rt-amd64
Found linux image: /boot/vmlinuz-3.2.0-4-amd64
Found initrd image: /boot/initrd.img-3.2.0-4-amd64
done
Setting up linux-headers-3.10.10-amd64-yomguy-rt7 (2) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 3.10.10-amd64-yomguy-rt7 /boot/vmlinuz-3.10.10-amd64-yomguy-rt7
Error!  Build of xt_ACCOUNT.ko failed for: 3.10.10-amd64-yomguy-rt7 (x86_64)
Consult the make.log in the build directory
/var/lib/dkms/xtables-addons/1.42/build/ for more information.

Hm.. I use Xtables-addons current kernel. Any suggestion?

**Comment by ghost** [comment]
DKMS make.log for xtables-addons-1.42 for kernel 3.10.10-amd64-yomguy-rt7 (x86_64)
Thu Dec 11 21:23:38 EET 2014
make: Entering directory `/usr/src/linux-headers-3.10.10-amd64-yomguy-rt7'
  CC [M]  /usr/src/xtables-addons-1.42/compat_xtables.o
  CC [M]  /usr/src/xtables-addons-1.42/xt_CHAOS.o
  CC [M]  /usr/src/xtables-addons-1.42/xt_DELUDE.o
  CC [M]  /usr/src/xtables-addons-1.42/xt_DHCPMAC.o
  CC [M]  /usr/src/xtables-addons-1.42/xt_DNETMAP.o
/usr/src/xtables-addons-1.42/xt_DNETMAP.c:29:39: fatal error: net/netfilter/nf_nat_rule.h: No such file or directory
compilation terminated.
make[1]: *** [/usr/src/xtables-addons-1.42/xt_DNETMAP.o] Error 1
make: *** [_module_/usr/src/xtables-addons-1.42] Error 2
make: Leaving directory`/usr/src/linux-headers-3.10.10-amd64-yomguy-rt7'

**Comment by yomguy** [comment]
Hi,
Sorry, but I've never tried Xtables-addons.. 
So you added it to the config before compiling right?

**Comment by ghost** [comment]
I tried both ways. Huh... looks kernel bug.

**Comment by yomguy** [comment]
Maybe you can try now with 4.1.2
